analysis/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    #Batsmen
    path('batsmen', views.Batsmen.as_view(), name = 'batsmen'),
    path('batsmen_top10', views.BatsmenTop10.as_view(), name = 'batsmen_top10'),
    path('batsmen_dismissal', views.BatsmenDismissal.as_view(), name = 'batsmen_dismissal'),
    path('batsmen_sixes', views.BatsmenSixes.as_view(), name = 'batsmen_sixes'),
    path('batsmen_fours', views.BatsmenFours.as_view(), name = 'batsmen_fours'),
    path('batsmen_match_wise', views.BatsmenMatchWise.as_view(), name = 'batsmen_match_wise'),

    #Bowler
    path('bowler', views.Bowler.as_view(), name = 'bowler'),
    path('bowler_top10', views.BowlerTop10.as_view(), name = 'bowler_top10'),
    path('bowler_match_wise', views.BowlerMatchWise.as_view(), name = 'bowler_match_wise'),
    # path('bowler_wickets', views.BowlerWickets.as_view(), name = 'bowler_wickets'),
    # path('bowlers_rival', views.BowlerRival.as_view(), name = 'bowlers_rival'),

    #Teams
    path('team', views.Team.as_view(), name = 'team'),
    path('team_stadium_name_with_max_win', views.TeamStadiumNameWithMaxWin.as_view(), name = 'team_stadium_name_with_max_win'),
    path('team_winning_percentage', views.WiningPercentage.as_view(), name = 'team_winning_percentage'),
    path('team_man_of_the_match', views.ManOfTheMatch.as_view(), name = 'team_man_of_the_match'),

    #Upload
    path('upload', views.Upload.as_view(), name = 'upload'),
    path('match_details', views.UploadMatchDetails.as_view(), name = 'match_details'),
    path('ball_details', views.UploadBallDetails.as_view(), name = 'ball_details'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('users', include('django.contrib.auth.urls')),
    path('users', include('users.urls', namespace = 'users')),
    path('analysis/', include('analysis.urls', namespace = 'analysis')),
    path('test', views.TestPage.as_view(), name = 'test'),
    path('thanks', views.ThanksPage.as_view(), name = 'thanks'),
]

analysis/models.py
from django.db import models

# Create your models here.
class Batsman(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    runs = models.IntegerField()

    def __str__(self):
        return self.name

class Bowler(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    wickets = models.IntegerField()

    def __str__(self):
        return self.name

class Stadium(models.Model):
    team = models.CharField(max_length = 255)
    ground = models.CharField(max_length = 255)

    def __str__(self):
        return self.team

analysis/forms.py
from django.db import models
from django.forms import ModelForm
from django import forms

YEAR_CHOICES = [('2008','2008'),('2009','2009'),('2010','2010'),
                ('2011','2011'),('2012','2012'),('2013','2013'),
                ('2014','2014'),('2015','2015'),('2016','2016'),
                ('2017','2017'),('2018','2018'),('2019','2019'),
                ('overall','Overall')]

TEAM_CHOICES = [('Royal Challengers Bangalore','Royal Challengers Bangalore'),
                ('Punjab Kings','Punjab Kings'),('Delhi Capitals','Delhi Capitals'),
                ('Mumbai Indians','Mumbai Indians'),
                ('Kolkata Knight Riders','Kolkata Knight Riders'),
                ('Rajasthan Royals','Rajasthan Royals'),
                ('Chennai Super Kings','Chennai Super Kings'),
                ('Kochi Tuskers Kerala','Kochi Tuskers Kerala'),
                ('Pune Warriors','Pune Warriors'),
                ('Sunrisers Hyderabad','Sunrisers Hyderabad'),
                ('Gujarat Lions','Gujarat Lions'),('Rising Pune Supergiant','Rising Pune Supergiant'),
                ('None','None')]

class Filter(models.Model):
    year = models.CharField(max_length=10,choices=YEAR_CHOICES,default='overall')
    team_name = models.CharField(max_length=50,choices=TEAM_CHOICES,default='None')

class Filter_year(models.Model):
    year = models.CharField(max_length=10,choices=YEAR_CHOICES,default='overall')


class UploadFileForm(forms.Form):
    file = forms.FileField()


class FilterForm(ModelForm):
  class Meta:
    model = Filter
    fields = '__all__'

class FilterYearForm(ModelForm):
  class Meta:
    model = Filter_year
    fields = '__all__'

analysis/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from . import models,forms
from pathlib import Path
from service.bowlers import BowlersService
from service.batsmen import BatsmenService
from service.team import TeamService
from service.upload import UploadService

# Create your views here.
#Batsmen's View classes
class Batsmen(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/batsmen/home.html')

class BatsmenTop10(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_top10.html',{'form':form_class})
    def post(self,request):
        batsmen_service = BatsmenService()
        file_path = batsmen_service.get_top_10_batsmen(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/batsmen/batsmen_top10.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BatsmenDismissal(LoginRequiredMixin, generic.ListView):
    def get(self,request):
        data = request.POST
        batsmen_service = BatsmenService()
        data = batsmen_service.get_top_batsman_dismissal()
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_dismissal.html',{'form':form_class,
                      'data':data})
    def post(self,request):
        data = request.POST
        batsmen_service = BatsmenService()
        data = batsmen_service.get_top_batsman_dismissal()
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_dismissal.html',{'form':form_class,
                      'data':data})


class BatsmenSixes(LoginRequiredMixin, generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_sixes.html',{'form':form_class})
    def post(self,request):
        batsmen_service = BatsmenService()
        file_path = batsmen_service.get_top_six_hitters(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/batsmen/batsmen_sixes.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BatsmenFours(LoginRequiredMixin, generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_fours.html',{'form':form_class})
    def post(self,request):
        batsmen_service = BatsmenService()
        file_path = batsmen_service.get_top_four_hitters(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/batsmen/batsmen_fours.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BatsmenMatchWise(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_match_wise.html',{'form':form_class})
    def post(self,request):
        data = request.POST
        batsmen_service = BatsmenService()
        match_wise_details = batsmen_service.get_batsmen_match_wise(data['year'])
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_match_wise.html',{'form':form_class,
                      'match_wise_details':match_wise_details})

#Bowler's View classes
class Bowler(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/bowler/home.html')

class BowlerTop10(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/bowler/bowler_top10.html',{'form':form_class})
    def post(self,request):
        bowler_Service = BowlersService()
        file_path = bowler_Service.get_top_10_bowlers(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/bowler/bowler_top10.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BowlerMatchWise(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/bowler/bowler_match_wise.html',{'form':form_class})
    def post(self,request):
        bowler_service = BowlersService()
        match_wise_details = bowler_service.get_bowlers_match_wise(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if match_wise_details is None:
            is_data_exist = False
        return render(request,'analysis/bowler/bowler_match_wise.html',{'form':form_class,
                      'match_wise_details':match_wise_details,'is_data_exist':is_data_exist})

#Teams's View classes
class Team(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/team/home.html')

class TeamStadiumNameWithMaxWin(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/team/team_stadium_name_max_win.html',{'form':form_class})
    def post(self,request):
        team_service = TeamService()
        data = request.POST
        file_path = team_service.get_stadium_name_with_max_win(data['year'], data['team_name'])
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/team/team_stadium_name_max_win.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class WiningPercentage(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/team/team_winning_percentage.html',{'form':form_class})
    def post(self,request):
        form_class = forms.FilterForm
        data = request.POST
        team_Service = TeamService()
        file_path = team_Service.get_winning_percentage(data['year'], data['team_name'])
        return render(request,'analysis/team/team_winning_percentage.html',{'form':form_class,
                      'file_path':file_path})

class ManOfTheMatch(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterYearForm
        return render(request,'analysis/team/team_man_of_the_match.html',{'form':form_class})
    def post(self,request):
        data = request.POST
        team_Service = TeamService()
        file_path = team_Service.get_man_of_the_match(data['year'])
        form_class = forms.FilterYearForm
        return render(request,'analysis/team/team_man_of_the_match.html',{'form':form_class,
                      'file_path':file_path})

#Upload's View classes
class Upload(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/upload/home.html')

class UploadMatchDetails(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/match_details.html',{'form':form_class})
    def post(self,request):
        form = forms.UploadFileForm(request.POST,request.FILES)
        upload_service = UploadService()
        result = upload_service.match_details(request)
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/match_details.html',
        {'form':form_class,'status_code':result})

class UploadBallDetails(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/ball_details.html',{'form':form_class})
    def post(self,request):
        form = forms.UploadFileForm(request.POST,request.FILES)
        upload_service = UploadService()
        result = upload_service.ball_details(request)
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/ball_details.html',
        {'form':form_class,'status_code':result})

templates/analysis/batsmen/batsman_dismissal.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main">
    <div class="sidebar">
      <ul>
        <li><a href="{% url 'analysis:batsmen_top10' %}"><i class=""></i><span>Top 10 Batsmen</span></a></li>
        <li><a href="" class="active"><i class=""></i><span>Batsman Dismisal</span></a></li>
        <li><a href="{% url 'analysis:batsman_score' %}"><i class=""></i><span>Runs Scored</span></a></li>
        <li><a href="{% url 'analysis:batsman_mom' %}""><i class=""></i><span>MOM Batsman</span></a></li>
        <li><a href="{% url 'analysis:batsmen_sixes' %}"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="{% url 'analysis:batsmen_fours' %}"><i class=""></i><span>Four Hitters</span></a></li>
      </ul>
    </div>
    <div class="page-content">
      <div class="content-selection">Select any one Match from the List :
        <select id="mySelect" onchange="npup.doSelect(this);">
          <option value="">Select</option>
          <option value="0">zero</option>
          <option value="1">one</option>
          <option value="2">two</option>
        </select>
      </div>
      <br>
      <div id="mySpecialElements">
        <div id="npup0" class="hidden">
          <h3>Division 0</h3>
          <p>Content for div 0.</p>
        </div>
        <div id="npup1" class="hidden">
          <h3>Division 1</h3>
          <p>This content for div 1</p>
        </div>
        <div id="npup2" class="hidden">
          <h3>Division 2</h3>
          <p>This is Div 2 content.</p>
        </div>
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/batsmen/batsmen_dismissal.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body_block %}

<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:batsmen_top10' %}"><i class=""></i><span>Top 10 Batsmen</span></a></li>
        <li><a href="{% url 'analysis:batsmen_match_wise' %}"><i class=""></i><span>Macth Wise</span></a></li>
        <li><a href="" class="active"><i class=""></i><span>Batsmen Dismisal</span></a></li>

        <li><a href="{% url 'analysis:batsmen_sixes' %}"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="{% url 'analysis:batsmen_fours' %}"><i class=""></i><span>Four Hitters</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <!-- <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
       </form> -->
        <h1>Batsman vs Bowler Head to Head</h1>
        {% if data %}
          <div class="col">
            <table class="styled_table">
              <thead>
                <th>Batsman</th>
                <th>Bowler</th>
                <th>No. of Times Dismissed</th>
              </thead>
            {% for value in data %}
              <tbody>
                <tr>
                  <td>{{ value.batsmen_name }}</td>
                  <td>{{ value.bowler_name }}</td>
                  <td>{{ value.no_of_wickets }}</td>
                </tr>
              </tbody>
            {% endfor %}
            </table>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/analysis/batsmen/batsmen_fours.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body_block %}


<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:batsmen_top10' %}"><i class=""></i><span>Top 10 Batsmen</span></a></li>
        <li><a href="{% url 'analysis:batsmen_match_wise' %}"><i class=""></i><span>Macth Wise</span></a></li>
        <li><a href="{% url 'analysis:batsmen_dismissal' %}"><i class=""></i><span>Batsmen Dismisal</span></a></li>
        <li><a href="{% url 'analysis:batsmen_sixes' %}"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="" class="active"><i class=""></i><span>Four Hitters</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
       </form>
        {% if file_path %}
        <img src={{file_path}} class="img-fluid" alt="Top10 Six Hitters">
        {% endif %}
        <br/>
        {% if is_data_exist == False %}
        <div class="alert alert-danger" role="alert">
            No Data To Display
        </div>
        {% endif %}
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/batsmen/batsmen_match_wise.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body_block %}
{% load static %}
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:batsmen_top10' %}"><i class=""></i><span>Top 10 Batsmen</span></a></li>
        <li><a href="" class="active"><i ></i><span>Macth Wise</span></a></li>
        <li><a href="{% url 'analysis:batsmen_dismissal' %}"><i class=""></i><span>Batsmen Dismisal</span></a></li>
        <li><a href="{% url 'analysis:batsmen_sixes' %}"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="{% url 'analysis:batsmen_fours' %}" class=""><i class=""></i><span>Four Hitters</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary" value="Submit">
     </form>
     <br>
      {% if match_wise_details %}
        <div class="col">
        {% for key,value in match_wise_details.items %}
         <h1 class="align-self-center">Match Held on {{ value.match_info.date }}</h1>
          <table class="styled_table">
            <thead>
              <th>City</th>
              <th>Venue</th>
              <th>Team 1</th>
              <th>Team 2</th>
            </thead>
            <tbody>
              <tr>
                <td>{{ value.match_info.city }}</td>
                <td>{{ value.match_info.venue }}</td>
                <td>{{ value.match_info.team_1 }}</td>
                <td>{{ value.match_info.team_2 }}</td>
              </tr>
            </tbody>
          </table>
          <h1>Batsmen Details</h1>
           <table class="styled_table">
            <thead>
              <th>Name</th>
              <th>Team</th>
              <th>Runs Scored</th>
              <th>Dismissal Type</th>
              <th>Dismissed Bowler</th>
            </thead>
          {% for batsman in value.batsman_info %}
            <tbody>
              <tr>
                <td>{{ batsman.name }}</td>
                <td>{{ batsman.team }}</td>
                <td>{{ batsman.runs_scored }}</td>
                {% if batsman.nature_of_dismissal == null %}
                  <td>Not Out</td>
                {% else %}
                  <td>{{ batsman.nature_of_dismissal }}</td>
                {% endif %}
                <td>{{ batsman.bowler_got_out }}</td>
              </tr>
            </tbody>
          {% endfor %}
          </table>
        {% endfor %}
      </div>
      {% endif %}
    </div>

    <!-- <div class="row">
      <picture>
        <img src="{% static 'graph/bowlers/top_10_bowlers.jpg' %}" class="img-fluid" alt="Top 10 Bowlers">
      </picture>
    </div> -->
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/batsmen/batsmen_sixes.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body_block %}


<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:batsmen_top10' %}"><i class=""></i><span>Top 10 Batsmen</span></a></li>
        <li><a href="{% url 'analysis:batsmen_match_wise' %}"><i class=""></i><span>Macth Wise</span></a></li>
        <li><a href="{% url 'analysis:batsmen_dismissal' %}"><i class=""></i><span>Batsmen Dismisal</span></a></li>

        <li><a href="" class="active"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="{% url 'analysis:batsmen_fours' %}"><i class=""></i><span>Four Hitters</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
       </form>
        {% if file_path %}
        <img src={{file_path}} class="img-fluid" alt="Top10 Six Hitters">
        {% endif %}
        <br/>
        {% if is_data_exist == False %}
        <div class="alert alert-danger" role="alert">
            No Data To Display
        </div>
        {% endif %}
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/batsmen/batsmen_top10.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block body_block %}

<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="" class="active"><i class=""></i><span>Top 10 Batsman</span></a></li>
        <li><a href="{% url 'analysis:batsmen_match_wise' %}"><i class=""></i><span>Macth Wise</span></a></li>
        <li><a href="{% url 'analysis:batsmen_dismissal' %}"><i class=""></i><span>Batsmen Dismisal</span></a></li>

        <li><a href="{% url 'analysis:batsmen_sixes' %}"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="{% url 'analysis:batsmen_fours' %}"><i class=""></i><span>Four Hitters</span></a></li>
    </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
       </form>
        {% if file_path %}
        <img src={{file_path}} class="img-fluid" alt="Top 10 Batsmen">
        {% endif %}
        <br/>
        {% if is_data_exist == False %}
        <div class="alert alert-danger" role="alert">
            No Data To Display
        </div>
      {% endif %}
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/batsmen/home.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:batsmen_top10' %}"><i class=""></i><span>Top 10 Batsmen</span></a></li>
        <li><a href="{% url 'analysis:batsmen_match_wise' %}"><i class=""></i><span>Macth Wise</span></a></li>
        <li><a href="{% url 'analysis:batsmen_dismissal' %}"><i class=""></i><span>Batsmen Dismisal</span></a></li>

        <li><a href="{% url 'analysis:batsmen_sixes' %}"><i class=""></i><span>Six Hitters</span></a></li>
        <li><a href="{% url 'analysis:batsmen_fours' %}"><i class=""></i><span>Four Hitters</span></a></li>
    </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <h1 align='center'>Welcome to Batsmen Analysis Page!!</h1>
      <div><img src="{% static 'images/batsman.jpg' %}" alt="batsman image" class="center-img" height="400rem"></div>
    </div>
  </div>
</div>
  </div>

{% endblock %}