analysis/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    #Batsmen
    path('batsmen', views.Batsmen.as_view(), name = 'batsmen'),
    path('batsmen_top10', views.BatsmenTop10.as_view(), name = 'batsmen_top10'),
    path('batsmen_dismissal', views.BatsmenDismissal.as_view(), name = 'batsmen_dismissal'),
    path('batsmen_sixes', views.BatsmenSixes.as_view(), name = 'batsmen_sixes'),
    path('batsmen_fours', views.BatsmenFours.as_view(), name = 'batsmen_fours'),
    path('batsmen_match_wise', views.BatsmenMatchWise.as_view(), name = 'batsmen_match_wise'),

    #Bowler
    path('bowler', views.Bowler.as_view(), name = 'bowler'),
    path('bowler_top10', views.BowlerTop10.as_view(), name = 'bowler_top10'),
    path('bowler_match_wise', views.BowlerMatchWise.as_view(), name = 'bowler_match_wise'),
    # path('bowler_wickets', views.BowlerWickets.as_view(), name = 'bowler_wickets'),
    # path('bowlers_rival', views.BowlerRival.as_view(), name = 'bowlers_rival'),

    #Teams
    path('team', views.Team.as_view(), name = 'team'),
    path('team_stadium_name_with_max_win', views.TeamStadiumNameWithMaxWin.as_view(), name = 'team_stadium_name_with_max_win'),
    path('team_winning_percentage', views.WiningPercentage.as_view(), name = 'team_winning_percentage'),
    path('team_man_of_the_match', views.ManOfTheMatch.as_view(), name = 'team_man_of_the_match'),

    #Upload
    path('upload', views.Upload.as_view(), name = 'upload'),
    path('match_details', views.UploadMatchDetails.as_view(), name = 'match_details'),
    path('ball_details', views.UploadBallDetails.as_view(), name = 'ball_details'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('users', include('django.contrib.auth.urls')),
    path('users', include('users.urls', namespace = 'users')),
    path('analysis/', include('analysis.urls', namespace = 'analysis')),
    path('test', views.TestPage.as_view(), name = 'test'),
    path('thanks', views.ThanksPage.as_view(), name = 'thanks'),
]

analysis/models.py
from django.db import models

# Create your models here.
class Batsman(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    runs = models.IntegerField()

    def __str__(self):
        return self.name

class Bowler(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    wickets = models.IntegerField()

    def __str__(self):
        return self.name

class Stadium(models.Model):
    team = models.CharField(max_length = 255)
    ground = models.CharField(max_length = 255)

    def __str__(self):
        return self.team

analysis/forms.py
from django.db import models
from django.forms import ModelForm
from django import forms

YEAR_CHOICES = [('2008','2008'),('2009','2009'),('2010','2010'),
                ('2011','2011'),('2012','2012'),('2013','2013'),
                ('2014','2014'),('2015','2015'),('2016','2016'),
                ('2017','2017'),('2018','2018'),('2019','2019'),
                ('overall','Overall')]

TEAM_CHOICES = [('Royal Challengers Bangalore','Royal Challengers Bangalore'),
                ('Punjab Kings','Punjab Kings'),('Delhi Capitals','Delhi Capitals'),
                ('Mumbai Indians','Mumbai Indians'),
                ('Kolkata Knight Riders','Kolkata Knight Riders'),
                ('Rajasthan Royals','Rajasthan Royals'),
                ('Chennai Super Kings','Chennai Super Kings'),
                ('Kochi Tuskers Kerala','Kochi Tuskers Kerala'),
                ('Pune Warriors','Pune Warriors'),
                ('Sunrisers Hyderabad','Sunrisers Hyderabad'),
                ('Gujarat Lions','Gujarat Lions'),('Rising Pune Supergiant','Rising Pune Supergiant'),
                ('None','None')]

class Filter(models.Model):
    year = models.CharField(max_length=10,choices=YEAR_CHOICES,default='overall')
    team_name = models.CharField(max_length=50,choices=TEAM_CHOICES,default='None')

class Filter_year(models.Model):
    year = models.CharField(max_length=10,choices=YEAR_CHOICES,default='overall')


class UploadFileForm(forms.Form):
    file = forms.FileField()


class FilterForm(ModelForm):
  class Meta:
    model = Filter
    fields = '__all__'

class FilterYearForm(ModelForm):
  class Meta:
    model = Filter_year
    fields = '__all__'

analysis/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from . import models,forms
from pathlib import Path
from service.bowlers import BowlersService
from service.batsmen import BatsmenService
from service.team import TeamService
from service.upload import UploadService

# Create your views here.
#Batsmen's View classes
class Batsmen(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/batsmen/home.html')

class BatsmenTop10(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_top10.html',{'form':form_class})
    def post(self,request):
        batsmen_service = BatsmenService()
        file_path = batsmen_service.get_top_10_batsmen(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/batsmen/batsmen_top10.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BatsmenDismissal(LoginRequiredMixin, generic.ListView):
    def get(self,request):
        data = request.POST
        batsmen_service = BatsmenService()
        data = batsmen_service.get_top_batsman_dismissal()
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_dismissal.html',{'form':form_class,
                      'data':data})
    def post(self,request):
        data = request.POST
        batsmen_service = BatsmenService()
        data = batsmen_service.get_top_batsman_dismissal()
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_dismissal.html',{'form':form_class,
                      'data':data})


class BatsmenSixes(LoginRequiredMixin, generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_sixes.html',{'form':form_class})
    def post(self,request):
        batsmen_service = BatsmenService()
        file_path = batsmen_service.get_top_six_hitters(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/batsmen/batsmen_sixes.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BatsmenFours(LoginRequiredMixin, generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_fours.html',{'form':form_class})
    def post(self,request):
        batsmen_service = BatsmenService()
        file_path = batsmen_service.get_top_four_hitters(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/batsmen/batsmen_fours.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BatsmenMatchWise(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_match_wise.html',{'form':form_class})
    def post(self,request):
        data = request.POST
        batsmen_service = BatsmenService()
        match_wise_details = batsmen_service.get_batsmen_match_wise(data['year'])
        form_class = forms.FilterForm
        return render(request,'analysis/batsmen/batsmen_match_wise.html',{'form':form_class,
                      'match_wise_details':match_wise_details})

#Bowler's View classes
class Bowler(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/bowler/home.html')

class BowlerTop10(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/bowler/bowler_top10.html',{'form':form_class})
    def post(self,request):
        bowler_Service = BowlersService()
        file_path = bowler_Service.get_top_10_bowlers(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/bowler/bowler_top10.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class BowlerMatchWise(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/bowler/bowler_match_wise.html',{'form':form_class})
    def post(self,request):
        bowler_service = BowlersService()
        match_wise_details = bowler_service.get_bowlers_match_wise(request.POST)
        form_class = forms.FilterForm
        is_data_exist = True
        if match_wise_details is None:
            is_data_exist = False
        return render(request,'analysis/bowler/bowler_match_wise.html',{'form':form_class,
                      'match_wise_details':match_wise_details,'is_data_exist':is_data_exist})

#Teams's View classes
class Team(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/team/home.html')

class TeamStadiumNameWithMaxWin(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/team/team_stadium_name_max_win.html',{'form':form_class})
    def post(self,request):
        team_service = TeamService()
        data = request.POST
        file_path = team_service.get_stadium_name_with_max_win(data['year'], data['team_name'])
        form_class = forms.FilterForm
        is_data_exist = True
        if file_path is None:
            is_data_exist = False
        return render(request,'analysis/team/team_stadium_name_max_win.html',{'form':form_class,
                      'file_path':file_path,'is_data_exist':is_data_exist})

class WiningPercentage(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterForm
        return render(request,'analysis/team/team_winning_percentage.html',{'form':form_class})
    def post(self,request):
        form_class = forms.FilterForm
        data = request.POST
        team_Service = TeamService()
        file_path = team_Service.get_winning_percentage(data['year'], data['team_name'])
        return render(request,'analysis/team/team_winning_percentage.html',{'form':form_class,
                      'file_path':file_path})

class ManOfTheMatch(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.FilterYearForm
        return render(request,'analysis/team/team_man_of_the_match.html',{'form':form_class})
    def post(self,request):
        data = request.POST
        team_Service = TeamService()
        file_path = team_Service.get_man_of_the_match(data['year'])
        form_class = forms.FilterYearForm
        return render(request,'analysis/team/team_man_of_the_match.html',{'form':form_class,
                      'file_path':file_path})

#Upload's View classes
class Upload(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        return render(request,'analysis/upload/home.html')

class UploadMatchDetails(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/match_details.html',{'form':form_class})
    def post(self,request):
        form = forms.UploadFileForm(request.POST,request.FILES)
        upload_service = UploadService()
        result = upload_service.match_details(request)
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/match_details.html',
        {'form':form_class,'status_code':result})

class UploadBallDetails(LoginRequiredMixin,  generic.ListView):
    def get(self,request):
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/ball_details.html',{'form':form_class})
    def post(self,request):
        form = forms.UploadFileForm(request.POST,request.FILES)
        upload_service = UploadService()
        result = upload_service.ball_details(request)
        form_class = forms.UploadFileForm
        return render(request,'analysis/upload/ball_details.html',
        {'form':form_class,'status_code':result})

templates/analysis/upload/ball_details.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body_block %}
{% load static %}
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:match_details' %}" ><i class=""></i><span>Match Details</span></a></li>
        <li><a href="" class = "active"><i class=""></i><span>Ball Details</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary" value="Upload">
     </form>
     <br/>

     {% if status_code >= 500 %}
        <div class="alert alert-danger" role="alert">
            Data Insertion Failed!
        </div>
      {% endif %}

     {% if status_code == 400 %}
        <div class="alert alert-danger" role="alert">
            Error While Insertion!
        </div>
      {% endif %}

      {% if status_code == 201 %}
        <div class="alert alert-success" role="alert">
            Data Insertion Successfull!
        </div>
      {% endif %}
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/upload/home.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="{% url 'analysis:match_details' %}"><i class=""></i><span>Match Details</span></a></li>
        <li><a href="{% url 'analysis:ball_details' %}"><i class=""></i><span>Ball Details</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <h1 align = "center">Welcome to Upload Section Page!!</h1>
      <div><img src="{% static 'images/upload.svg' %}" alt="bowlers image" class="center-img" height="400rem"></div>
    </div>
  </div>
</div>
  </div>

{% endblock %}

templates/analysis/upload/match_details.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body_block %}
{% load static %}
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <div class="main row">
    <div class="sidebar col-sm-6 col-lg-3 col-md-3">
      <ul>
        <li><a href="" class = "active"><i class=""></i><span>Match Details</span></a></li>
        <li><a href="{% url 'analysis:ball_details' %}"><i class=""></i><span>Ball Details</span></a></li>
      </ul>
    </div>
    <div class="page-content col-sm-6 col-lg-9 col-md-9">
      <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-primary" value="Upload">
     </form>
     <br/>

     {% if status_code >= 500 %}
        <div class="alert alert-danger" role="alert">
            Data Insertion Failed!
        </div>
      {% endif %}

     {% if status_code == 400 %}
        <div class="alert alert-danger" role="alert">
            Error While Insertion!
        </div>
      {% endif %}

      {% if status_code == 201 %}
        <div class="alert alert-success" role="alert">
            Data Insertion Successfull!
        </div>
      {% endif %}

    </div>
  </div>
</div>
  </div>

{% endblock %}