analysis/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    #Batsmen
    path('batsmen', views.Batsmen.as_view(), name = 'batsmen'),
    path('batsmen_top10', views.BatsmenTop10.as_view(), name = 'batsmen_top10'),
    path('batsmen_dismissal', views.BatsmenDismissal.as_view(), name = 'batsmen_dismissal'),
    path('batsmen_sixes', views.BatsmenSixes.as_view(), name = 'batsmen_sixes'),
    path('batsmen_fours', views.BatsmenFours.as_view(), name = 'batsmen_fours'),
    path('batsmen_match_wise', views.BatsmenMatchWise.as_view(), name = 'batsmen_match_wise'),

    #Bowler
    path('bowler', views.Bowler.as_view(), name = 'bowler'),
    path('bowler_top10', views.BowlerTop10.as_view(), name = 'bowler_top10'),
    path('bowler_match_wise', views.BowlerMatchWise.as_view(), name = 'bowler_match_wise'),
    # path('bowler_wickets', views.BowlerWickets.as_view(), name = 'bowler_wickets'),
    # path('bowlers_rival', views.BowlerRival.as_view(), name = 'bowlers_rival'),

    #Teams
    path('team', views.Team.as_view(), name = 'team'),
    path('team_stadium_name_with_max_win', views.TeamStadiumNameWithMaxWin.as_view(), name = 'team_stadium_name_with_max_win'),
    path('team_winning_percentage', views.WiningPercentage.as_view(), name = 'team_winning_percentage'),
    path('team_man_of_the_match', views.ManOfTheMatch.as_view(), name = 'team_man_of_the_match'),

    #Upload
    path('upload', views.Upload.as_view(), name = 'upload'),
    path('match_details', views.UploadMatchDetails.as_view(), name = 'match_details'),
    path('ball_details', views.UploadBallDetails.as_view(), name = 'ball_details'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('users', include('django.contrib.auth.urls')),
    path('users', include('users.urls', namespace = 'users')),
    path('analysis/', include('analysis.urls', namespace = 'analysis')),
    path('test', views.TestPage.as_view(), name = 'test'),
    path('thanks', views.ThanksPage.as_view(), name = 'thanks'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup', views.SignUp.as_view(), name = 'signup')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>IPL Analysis</title>

    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400italic,700italic">

  </head>
  <body>
    <nav class="navbar navbar-expand-md mynav bg-light" role="navigation" id="navbar">
      <div class="container">

          <ul class="nav navbar">
            <li><a class="navbar-brand mynav" href="{% url 'home' %}">Home!</a></li>
            <li><a href="{% url 'admin:index' %}" class="btn btn-simple nav-link">Admin</a></li>
          </ul>
          <ul class="nav navbar">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
              <div class=""><img  height="40px" width="50px" src="{% static 'images/toggle2.png' %}"></img></div>
              <!-- <span class="icon-bar bg-dark"></span>
              <span class="icon-bar bg-dark"></span>
              <span class="icon-bar bg-dark"></span> -->
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
            {% if user.is_authenticated %}
                  <li class="nav-item"><a href="{% url 'analysis:upload' %}" class="nav-link">Upload</a></li>
                  <li class="nav-item"><a href="{% url 'analysis:batsmen' %}" class="nav-link">Batsmen</a></li>
                  <li class="nav-item"><a href="{% url 'analysis:bowler' %}" class="nav-link">Bowler</a></li>
                  <li class="nav-item"><a href="{% url 'analysis:team' %}" class="nav-link">Team</a></li>
                  <li class="nav-item"><a href="{% url 'users:logout' %}" class="nav-link">Log out</a></li>
            {% else %}
                  <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link">Log in</a></li>
                  <li class="nav-item"><a href="{% url 'users:signup' %}" class="nav-link">Sign up</a></li>
            {% endif %}
        </div>
      </ul>
      </div>
    </nav>
    <br>
    <div class="container mycontent">
    {% block body_block %}

    {% endblock %}
  </div>
  <canvas id="canvas" ></canvas>
  <!-- <script src="{% static 'js/master.js' %}"></script> -->

  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script> -->
  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script> -->
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
<!-- <h1>Welcome to Home Page!!</h1> -->
<div class="container container__item landing-page-container", align = 'center'>
  <div class="content__wrapper jumbotron">
    <div class="row">
    <header class="header">
          <h1 class="heading header__item">Welcome to IPL Analysis Website!</h1><br>
    </header>
    <div class="col-lg-6 col-md-12">
    <h4 align = 'left'>About the Project:</h4>
    <p align='justify'>Our Website shows multiple Analysis of the Batsmen, Bowlers and Teams participated in Indian Premier League. The analysis is based on the factual data of each matches that are conducted in IPL tournament between the years 2008 - 2020.</p>
    <p align='justify'>To view the reports made for each stream of the game, the users are requested to create an account in our website by providing required credentials. The provided data by the users are protected and are maintained with respect to our website’s privacy policy. After creating the account, the users can view the batsmen, bowlers and teams reports in its respective tabs displayed in the top right corner of the screen.</p>
    <p align='justify'>For any issues in the website, please contact:</p>
      <ul>
        <li align='left'><a href="mailto: 142102014@smail.iitpkd.ac.in?subject=Feedback for IPL Analysis Website - to Vasanthan" class='a-name'>Vasanthan PV</a></li>
        <li align='left'><a href="mailto: 142102002@smail.iitpkd.ac.in?subject=Feedback for IPL Analysis Website - to Anurag" class='a-name'>Anurag Kr. Singh</a></li>
        <li align='left'><a href="mailto: 142102007@smail.iitpkd.ac.in?subject=Feedback for IPL Analysis Website - to Favaz" class='a-name'>Favaz Muhammed</a></li>
      </ul>
  </div>
      <div class="col-lg-6 col-sm-12">
        <div><img src="{% static 'images/home1.jpg' %}" alt="ipl image" class="center-img-home" height="450rem"></div>
      </div>
      </div>
    </div>
    <p align='center'>©2021 Indian Institute of Technology, Palakkkad </p>
    </div>

{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
<!-- <h1>Welcome to Home Page!!</h1> -->
<div class="container container__item landing-page-container", align = 'center'>
  <div class="content__wrapper green_jumbotron">
    <h6><i>You are now logged in!!! We welcome you to explore our website!!!</i></h6>
  </div>
  <div class="content__wrapper jumbotron">
    <div class="row">
    <header class="header">
          <h1 class="heading header__item">Welcome to IPL Analysis Website!</h1><br>
    </header>
    <div class="col-lg-6 col-md-12">
    <h4 align = 'left'>About the Project:</h4>
    <p align='justify'>Our Website shows multiple Analysis of the Batsmen, Bowlers and Teams participated in Indian Premier League. The analysis is based on the factual data of each matches that are conducted in IPL tournament between the years 2008 - 2020.</p>
    <p align='justify'>To view the reports made for each stream of the game, the users are requested to create an account in our website by providing required credentials. The provided data by the users are protected and are maintained with respect to our website’s privacy policy. After creating the account, the users can view the batsmen, bowlers and teams reports in its respective tabs displayed in the top right corner of the screen.</p>
    <p align='justify'>For any issues in the website, please contact:</p>
      <ul>
        <li align='left'><a href="mailto: 142102014@smail.iitpkd.ac.in?subject=Feedback for IPL Analysis Website - to Vasanthan" class='a-name'>Vasanthan PV</a></li>
        <li align='left'><a href="mailto: 142102002@smail.iitpkd.ac.in?subject=Feedback for IPL Analysis Website - to Anurag" class='a-name'>Anurag Kr. Singh</a></li>
        <li align='left'><a href="mailto: 142102007@smail.iitpkd.ac.in?subject=Feedback for IPL Analysis Website - to Favaz" class='a-name'>Favaz Muhammed</a></li>
      </ul>
  </div>
      <div class="col-lg-6 col-sm-12">
        <div><img src="{% static 'images/home1.jpg' %}" alt="ipl image" class="center-img-home" height="450rem"></div>
      </div>
      </div>
    </div>
    <p align='center'>©2021 Indian Institute of Technology, Palakkkad </p>
    </div>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block body_block %}
<!-- <h1>Welcome to Home Page!!</h1> -->
<div class="container container__item landing-page-container">
  <div class="content__wrapper">
    <header class="header">

          <h1 class="heading header__item">Thanks for Logging in. Come back soon!</h1>
        </header>

      </div>

    </div>

{% endblock %}